### ISSUE TITLE
Error running mesh.py

### ISSUE THREAD

**Issue by stuaxo** [adamlwgriffiths/OMGL#4]
Slightly weird error when I try mesh.py - other examples seem similar:

```
$ python mesh.py 
Traceback (most recent call last):
  File "mesh.py", line 32, in <module>
    from OpenGL import GL
  File "/mnt/data/home/stu/.virtualenvs/3d/local/lib/python2.7/site-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL.GL.VERSION.GL_1_1 import *
  File "/mnt/data/home/stu/.virtualenvs/3d/local/lib/python2.7/site-packages/OpenGL/GL/VERSION/GL_1_1.py", line 10, in <module>
    from OpenGL import platform, constants, constant, arrays
  File "/mnt/data/home/stu/.virtualenvs/3d/local/lib/python2.7/site-packages/OpenGL/arrays/__init__.py", line 19, in <module>
    from OpenGL.arrays.arraydatatype import *
  File "/mnt/data/home/stu/.virtualenvs/3d/local/lib/python2.7/site-packages/OpenGL/arrays/arraydatatype.py", line 14, in <module>
    from OpenGL_accelerate.arraydatatype import ArrayDatatype as ADT
  File "arraydatatype.pyx", line 1, in init OpenGL_accelerate.arraydatatype (src/arraydatatype.c:10964)
  File "wrapper.pyx", line 3, in init OpenGL_accelerate.wrapper (src/wrapper.c:11183)
  File "/mnt/data/home/stu/.virtualenvs/3d/local/lib/python2.7/site-packages/OpenGL/error.py", line 224, in <module>
    ErrorChecker = _ErrorChecker( platform )
  File "errorchecker.pyx", line 17, in OpenGL_accelerate.errorchecker._ErrorChecker.__init__ (src/errorchecker.c:818)
TypeError: __init__() takes at least 2 positional arguments (1 given)
```

**Comment by adamlwgriffiths** [comment]
This looks like a PyOpenGL issue.
The only OMGL code that has been run is the import `from OpenGL import GL`.
If you open up a python REPL and just enter in that import, I'm sure you'll see the same error.
The last time I ran the code I didn't have any issues, so it looks like they've broken something.
I'd raise an issue, although they seem to use sourceforge..... for some god-forsaken reason.

You could try an older version:
https://pypi.python.org/pypi/PyOpenGL

Alternatively, you could try this code I found to disable their error checking code:

```
import OpenGL
OpenGL.ERROR_CHECKING = False
```

**Comment by stuaxo** [comment]
I had a fiddle around and got to an error about sub_mesh being missing

```
$ python examples/mesh.py 
Traceback (most recent call last):
  File "examples/mesh.py", line 37, in <module>
    from omgl.mesh import Mesh
  File "examples/../omgl/mesh/__init__.py", line 5, in <module>
    from .sub_mesh import *
ImportError: No module named sub_mesh
```

Indeed there is no mesh/sub_mesh.py

I'm still going to try and break it in the original way again to see if I can track down whats happening there.

**Comment by adamlwgriffiths** [comment]
Ah yes, the old "still works because of lingering .pyc files", my nemesis.

**Comment by adamlwgriffiths** [comment]
Removed invalid import in 5c64cf13d4942bb7a08ecad5d61949fe35cb57ae

**Comment by adamlwgriffiths** [comment]
I just did a fresh install from pypi of all dependencies and have no trouble running OMGL examples running Python 2.7 on OS-X.

**Comment by adamlwgriffiths** [comment]
Assuming closed

**Comment by stuaxo** [comment]
Confirming this works, cheers :)
